### ISSUE TITLE
[RadClass] np.where fails when start_time is not in timestamps

### ISSUE THREAD

**Issue by stompsjo** [CNERG/RadClass#26]
https://github.com/CNERG/RadClass/blob/ae1c71cd7c2e2c0077b244c9f6d05453445749ec/RadClass/RadClass.py#L98-L107

`np.where` will fail if the input epoch timestamp (either `start_time` or `stop_time`) is not in the `DataSet.timestamps` vector. This means RadClass will crash with an error. I think the most logical solution is to implement some sort of if-then that defaults to the first or last timestamp in the vector if the user value is not available. Alternatively, we could implement a method that finds the _nearest_ timestamp, whether than is identical or a few seconds off.

**Comment by gonuke** [comment]
Probably want the nearest time < start time and the nearest time > stop time as your range.

**Comment by stompsjo** [comment]
Addressed in #28
