### ISSUE TITLE
[RadClass.RadClass] IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by stompsjo** [CNERG/RadClass#35]
This line produces the above error:
https://github.com/CNERG/RadClass/blob/70b70624e41fee2e0a6229c7ab7aa4f3249b5a0f/RadClass/RadClass.py#L95
This is occurring when `self.processor.timestamps >= self.stop_time` produces no `True` values. i.e. there are no timestamps in the given dataset that are larger than the user's `stop_time`. In this case, the default `stop_time` timestamp should just be the last timestamp in the vector.

Thoughts on how to implement? Perhaps some measure that first checks if `self.processor.timestamps[self.processor.timestamps >= self.stop_time]` is empty and, if not, index the first timestamp. Otherwise, default to the last in `self.processor.timestamps`.

**Comment by stompsjo** [comment]
A possible [solution...](https://github.com/stompsjo/RadClass/blob/58db000b645bec0451ecf997222e73e9ad2c81ce/RadClass/RadClass.py#L112)

**Comment by gonuke** [comment]
There are actually a few logical cases to be sure we have considered given the relationship between the set of timestamps and the start/stop times...

In line 95... if there are no timestamps > than the start time, then isn't the result the empty set?

**Comment by gonuke** [comment]
Given that any set of timestamps will have a minimum times stamp (let's call this `nts`) and a maximum timestep. (let's calls this `xts`) then you have the following cases:
1. no start time specificed
2. start time < nts
3. nts < start time < xts
4. xts < start time

And then the same set of combinations for the stop time, although not all 16 combinations exist if stop time is >= start time.

**Comment by stompsjo** [comment]
This is a good summary. I made a PR with a possible solution. We could raise `ValueError` (or some equivalent) when the inputted start/stop times are invalid. This would basically be case 4, stop_time < nts, and start_time >= stop_time.

As for the other cases, if no start time is specified, the default should be the first possible timestamp, likewise for case 2. In case 3, the code should act as it did before (with `np.searchsorted`).

**Comment by stompsjo** [comment]
Resolved by #36, closing.
